### Get all contacts
GET https://cse341-project-1-hvl8.onrender.com/contacts

### Get single contact
GET https://cse341-project-1-hvl8.onrender.com/contacts/6830c1332164274e3bf8b9b3

### POST new contact  
POST https://cse341-project-1-hvl8.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Don",
    "lastName": "Carlos",
    "email": "juan.don@gmail.com",
    "favoriteColor": "green",
    "birthday": "1905-05-16"
}

### PUT update contact
PUT https://cse341-project-1-hvl8.onrender.com/contacts/CONTACT_ID_HERE
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Don",
    "email": "juan.don@gmail.com",
    "favoriteColor": "red",
    "birthday": "1975-05-16"
}

### DELETE contact
DELETE https://cse341-project-1-hvl8.onrender.com/contacts/CONTACT_ID_HERE